name: Context Output

on: [push]

jobs:
  one:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Dump GitHub Context
        shell: pwsh
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: Write-Host "$GITHUB_CONTEXT"
        
      - name: Dump Job Context
        shell: pwsh
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: Write-Host "$JOB_CONTEXT"
        
      - name: Dump Steps Context
        shell: pwsh
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: Write-Host "$STEPS_CONTEXT"
        
      - name: Dump Runner Context
        shell: pwsh
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: Write-Host "$RUNNER_CONTEXT"
        
      - name: Dump Strategy Context
        shell: pwsh
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: Write-Host "$STRATEGY_CONTEXT"
        
      - name: Dump Matrix Context
        shell: pwsh
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: Write-Host "$MATRIX_CONTEXT"
