name: PowerShell Environment

on: [push]

jobs:
  one:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Dump PowerShell Environment
        shell: pwsh
        run: $PSVersionTable | Out-Default

    steps:
      - name: Dump OS
        shell: pwsh
        run: $PSVersionTable.OS | Out-Default
